[build]
command = "npm run build"
functions = "netlify/functions"
publish = "."

[[redirects]]
from = "/api/mock"
to = "/.netlify/functions/mock"
status = 200

[[redirects]]
from = "/api/mock/*"
to = "/.netlify/functions/mock"
status = 200
